### ISSUE TITLE
Only 360p muxed stream is returning

### ISSUE THREAD

**Issue by tingreavinash** [kotvertolet/YoutubeJExtractor#71]
I am using this library for fetching direct video url of youtube video link. This library is very helpful in extracting data. However, I am only getting one result from `getMuxedStreams()` API and it is of 360p qaulity. 

The original video has many formats like 720p, 1080p etc. I am missing something here?

**Code block:**
```java
        YoutubeJExtractor youtubeJExtractor = new YoutubeJExtractor();
        VideoPlayerConfig videoData;
        try {
            Log.v(TAG, "Getting video data");
            videoData = youtubeJExtractor.extract("tx-Mh7kH9SY");
            List<AdaptiveFormatsItem> formats = videoData.getStreamingData().getAdaptiveFormats();

            List<MuxedStream> muxedList =  videoData.getStreamingData().getMuxedStreams();

            Log.v(TAG, "List size of muxedList: "+muxedList.size()); // Returning only one object with URL or 360p video

        }
```

**Comment by antonyhaman** [comment]
@tingreavinash It works that way, I don't know why but youtube sometimes has several muxed streams for the video and sometimes it doesn't. 
>The original video has many formats like 720p, 1080p etc. 

As far as my knowledge go youtube player combines separate audio and video streams to achieve that, not muxed streams.
